version: "3.8"
services:
  relationship-bot:
    container_name: relationship-bot
    build:
      context: .
      dockerfile: ./docker/Dockerfile.relationship-bot
    env:
      - TOKEN=${TOKEN}
      - DBLTOKEN=${DBLTOKEN}
      - GRAPHVIZ=${GRAPHVIZ}
      - ERRORCHANNEL=${ERRORCHANNEL}
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=relationships
    restart: always